/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-25 08:34:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("author: W3layouts\r\n");
      out.write("author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Grocery Store a Ecommerce Online Shopping Category Flat Bootstrap Responsive Website Template | About Us :: w3layouts</title>\r\n");
      out.write("<!-- for-mobile-apps -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Grocery Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("\t\tfunction hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!-- //for-mobile-apps -->\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" /> \r\n");
      out.write("<!-- //font-awesome icons -->\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<!-- //js -->\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("</head>\r\n");
      out.write("\t\r\n");
      out.write("<body>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("\t<div class=\"agileits_header\">\r\n");
      out.write("\t\t<div class=\"w3l_offers\">\r\n");
      out.write("\t\t\t<a href=\"products.jsp\">Today's special Offers !</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3l_search\">\r\n");
      out.write("\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"Product\" value=\"Search a product...\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Search a product...';}\" required=\"\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\" \">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"product_list_header\">  \r\n");
      out.write("\t\t\t<form action=\"#\" method=\"post\" class=\"last\">\r\n");
      out.write("                <fieldset>\r\n");
      out.write("                    <input type=\"hidden\" name=\"cmd\" value=\"_cart\" />\r\n");
      out.write("                    <input type=\"hidden\" name=\"display\" value=\"1\" />\r\n");
      out.write("                    <input type=\"submit\" name=\"submit\" value=\"View your cart\" class=\"button\" />\r\n");
      out.write("                </fieldset>\r\n");
      out.write("            </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3l_header_right\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown profile_details_drop\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"fa fa-user\" aria-hidden=\"true\"></i><span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<div class=\"mega-dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"w3ls_vegetables\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu drp-mnu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"login.jsp\">Login</a></li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"login.jsp\">Sign Up</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>                  \r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3l_header_right1\">\r\n");
      out.write("\t\t\t<h2><a href=\"mail.jsp\">Contact Us</a></h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- script-for sticky-nav -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t var navoffeset=$(\".agileits_header\").offset().top;\r\n");
      out.write("\t\t $(window).scroll(function(){\r\n");
      out.write("\t\t\tvar scrollpos=$(window).scrollTop(); \r\n");
      out.write("\t\t\tif(scrollpos >=navoffeset){\r\n");
      out.write("\t\t\t\t$(\".agileits_header\").addClass(\"fixed\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\".agileits_header\").removeClass(\"fixed\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t \r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //script-for sticky-nav -->\r\n");
      out.write("\t<div class=\"logo_products\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"w3ls_logo_products_left\">\r\n");
      out.write("\t\t\t\t<h1><a href=\"index.jsp\"><span>Grocery</span> Store</a></h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3ls_logo_products_left1\">\r\n");
      out.write("\t\t\t\t<ul class=\"special_items\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"events.jsp\">Events</a><i>/</i></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"about.jsp\">About Us</a><i>/</i></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"products.jsp\">Best Deals</a><i>/</i></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"services.jsp\">Services</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3ls_logo_products_left1\">\r\n");
      out.write("\t\t\t\t<ul class=\"phone_email\">\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fa fa-phone\" aria-hidden=\"true\"></i>(+0123) 234 567</li>\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fa fa-envelope-o\" aria-hidden=\"true\"></i><a href=\"mailto:store@grocery.com\">store@grocery.com</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //header -->\r\n");
      out.write("<!-- products-breadcrumb -->\r\n");
      out.write("\t<div class=\"products-breadcrumb\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><i class=\"fa fa-home\" aria-hidden=\"true\"></i><a href=\"index.jsp\">Home</a><span>|</span></li>\r\n");
      out.write("\t\t\t\t<li>About Us</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //products-breadcrumb -->\r\n");
      out.write("<!-- banner -->\r\n");
      out.write("\t<div class=\"banner\">\r\n");
      out.write("\t\t<div class=\"w3l_banner_nav_left\">\r\n");
      out.write("\t\t\t<nav class=\"navbar nav_bottom\">\r\n");
      out.write("\t\t\t <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t  <div class=\"navbar-header nav_2\">\r\n");
      out.write("\t\t\t\t  <button type=\"button\" class=\"navbar-toggle collapsed navbar-toggle1\" data-toggle=\"collapse\" data-target=\"#bs-megadropdown-tabs\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t  </button>\r\n");
      out.write("\t\t\t   </div> \r\n");
      out.write("\t\t\t   <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"bs-megadropdown-tabs\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav nav_1\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"products.jsp\">Branded Foods</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"household.jsp\">Households</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown mega-dropdown active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Veggies & Fruits<span class=\"caret\"></span></a>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu mega-dropdown-menu w3ls_vegetables_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w3ls_vegetables\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"vegetables.jsp\">Vegetables</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"vegetables.jsp\">Fruits</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>                  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"kitchen.jsp\">Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"short-codes.jsp\">Short Codes</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Beverages<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu mega-dropdown-menu w3ls_vegetables_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w3ls_vegetables\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"drinks.jsp\">Soft Drinks</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"drinks.jsp\">Juices</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>                  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pet.jsp\">Pet Food</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Frozen Foods<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu mega-dropdown-menu w3ls_vegetables_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w3ls_vegetables\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"frozen.jsp\">Frozen Snacks</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"frozen.jsp\">Frozen Nonveg</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>                  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"bread.jsp\">Bread & Bakery</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t </div><!-- /.navbar-collapse -->\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3l_banner_nav_right\">\r\n");
      out.write("<!-- about -->\r\n");
      out.write("\t\t<div class=\"privacy about\">\r\n");
      out.write("\t\t\t<h3>About Us</h3>\r\n");
      out.write("\t\t\t<p class=\"animi\">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis \r\n");
      out.write("\t\t\t\tpraesentium voluptatum deleniti atque corrupti quos dolores et quas molestias \r\n");
      out.write("\t\t\t\texcepturi sint occaecati cupiditate non provident, similique sunt in culpa qui \r\n");
      out.write("\t\t\t\tofficia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem \r\n");
      out.write("\t\t\t\trerum facilis est et expedita distinctio.</p>\r\n");
      out.write("\t\t\t<div class=\"agile_about_grids\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 agile_about_grid_right\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/31.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 agile_about_grid_left\">\r\n");
      out.write("\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t<li>laborum et dolorum fuga</li>\r\n");
      out.write("\t\t\t\t\t\t<li>corrupti quos dolores et quas</li>\r\n");
      out.write("\t\t\t\t\t\t<li>est et expedita distinctio</li>\r\n");
      out.write("\t\t\t\t\t\t<li>deleniti atque corrupti quos</li>\r\n");
      out.write("\t\t\t\t\t\t<li>excepturi sint occaecati cupiditate</li>\r\n");
      out.write("\t\t\t\t\t\t<li>accusamus et iusto odio</li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!-- //about -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //banner -->\r\n");
      out.write("<!-- team -->\r\n");
      out.write("\t<div class=\"team\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h3>Meet Our Amazing Team</h3>\r\n");
      out.write("\t\t\t<div class=\"agileits_team_grids\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 agileits_team_grid\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/32.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t<h4>Martin Paul</h4>\r\n");
      out.write("\t\t\t\t\t<p>Manager</p>\r\n");
      out.write("\t\t\t\t\t<ul class=\"agileits_social_icons agileits_social_icons_team\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"google\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 agileits_team_grid\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/33.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t<h4>Michael Rick</h4>\r\n");
      out.write("\t\t\t\t\t<p>Supervisor</p>\r\n");
      out.write("\t\t\t\t\t<ul class=\"agileits_social_icons agileits_social_icons_team\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"google\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 agileits_team_grid\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/34.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t<h4>Thomas Carl</h4>\r\n");
      out.write("\t\t\t\t\t<p>Supervisor</p>\r\n");
      out.write("\t\t\t\t\t<ul class=\"agileits_social_icons agileits_social_icons_team\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"google\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 agileits_team_grid\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/35.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t<h4>Laura Lee</h4>\r\n");
      out.write("\t\t\t\t\t<p>CEO</p>\r\n");
      out.write("\t\t\t\t\t<ul class=\"agileits_social_icons agileits_social_icons_team\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"google\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //team -->\r\n");
      out.write("<!-- testimonials -->\r\n");
      out.write("\t<div class=\"testimonials\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h3>Testimonials</h3>\r\n");
      out.write("\t\t\t\t<div class=\"w3_testimonials_grids\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wmuSlider example1 animated wow slideInUp\" data-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wmuSliderWrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t<article style=\"position: absolute; width: 100%; opacity: 0;\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 w3_testimonials_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p><i class=\"fa fa-quote-right\" aria-hidden=\"true\"></i>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvoluptatibus maiores alias consequatur aut perferendis doloribus asperiores \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trepellat.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>Andrew Smith <span>Customer</span></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 w3_testimonials_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p><i class=\"fa fa-quote-right\" aria-hidden=\"true\"></i>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvoluptatibus maiores alias consequatur aut perferendis doloribus asperiores \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trepellat.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>Thomson Richard <span>Customer</span></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t\t<article style=\"position: absolute; width: 100%; opacity: 0;\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 w3_testimonials_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p><i class=\"fa fa-quote-right\" aria-hidden=\"true\"></i>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvoluptatibus maiores alias consequatur aut perferendis doloribus asperiores \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trepellat.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>Crisp Kale <span>Customer</span></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 w3_testimonials_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p><i class=\"fa fa-quote-right\" aria-hidden=\"true\"></i>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvoluptatibus maiores alias consequatur aut perferendis doloribus asperiores \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trepellat.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>John Paul <span>Customer</span></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t\t<article style=\"position: absolute; width: 100%; opacity: 0;\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 w3_testimonials_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p><i class=\"fa fa-quote-right\" aria-hidden=\"true\"></i>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvoluptatibus maiores alias consequatur aut perferendis doloribus asperiores \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trepellat.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>Rosy Carl <span>Customer</span></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 w3_testimonials_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p><i class=\"fa fa-quote-right\" aria-hidden=\"true\"></i>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvoluptatibus maiores alias consequatur aut perferendis doloribus asperiores \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trepellat.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>Rockson Doe <span>Customer</span></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<script src=\"js/jquery.wmuSlider.js\"></script> \r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t$('.example1').wmuSlider();         \r\n");
      out.write("\t\t\t\t\t</script> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //testimonials -->\r\n");
      out.write("<!-- newsletter -->\r\n");
      out.write("\t<div class=\"newsletter\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"w3agile_newsletter_left\">\r\n");
      out.write("\t\t\t\t<h3>sign up for our newsletter</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3agile_newsletter_right\">\r\n");
      out.write("\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"email\" name=\"Email\" value=\"Email\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Email';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"subscribe now\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //newsletter -->\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>information</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"events.jsp\">Events</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"about.jsp\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"products.jsp\">Best Deals</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"services.jsp\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"short-codes.jsp\">Short Codes</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>policy info</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"faqs.jsp\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"privacy.jsp\">privacy policy</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"privacy.jsp\">terms of use</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>what in stores</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"pet.jsp\">Pet Food</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"frozen.jsp\">Frozen Snacks</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"kitchen.jsp\">Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"products.jsp\">Branded Foods</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"household.jsp\">Households</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>twitter posts</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list1\">\r\n");
      out.write("\t\t\t\t\t<li><label class=\"fa fa-twitter\" aria-hidden=\"true\"></label><i>01 day ago</i><span>Non numquam <a href=\"#\">http://sd.ds/13jklf#</a>\r\n");
      out.write("\t\t\t\t\t\teius modi tempora incidunt ut labore et\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">http://sd.ds/1389kjklf#</a>quo nulla.</span></li>\r\n");
      out.write("\t\t\t\t\t<li><label class=\"fa fa-twitter\" aria-hidden=\"true\"></label><i>02 day ago</i><span>Con numquam <a href=\"#\">http://fd.uf/56hfg#</a>\r\n");
      out.write("\t\t\t\t\t\teius modi tempora incidunt ut labore et\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">http://fd.uf/56hfg#</a>quo nulla.</span></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t<div class=\"agile_footer_grids\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 w3_footer_grid agile_footer_grids_w3_footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3_footer_grid_bottom\">\r\n");
      out.write("\t\t\t\t\t\t<h4>100% secure payments</h4>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/card.png\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 w3_footer_grid agile_footer_grids_w3_footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3_footer_grid_bottom\">\r\n");
      out.write("\t\t\t\t\t\t<h5>connect with us</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"agileits_social_icons\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"google\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"instagram\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"dribbble\"><i class=\"fa fa-dribbble\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"wthree_footer_copy\">\r\n");
      out.write("\t\t\t\t<p>짤 2016 Grocery Store. All rights reserved | Design by <a href=\"http://w3layouts.com/\">W3layouts</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //footer -->\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\".dropdown\").hover(            \r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideDown(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');        \r\n");
      out.write("        },\r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideUp(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');       \r\n");
      out.write("        }\r\n");
      out.write("    );\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- here stars scrolling icon -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$().UItoTop({ easingType: 'easeOutQuart' });\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //here ends scrolling icon -->\r\n");
      out.write("<script src=\"js/minicart.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\tpaypal.minicart.render();\r\n");
      out.write("\r\n");
      out.write("\t\tpaypal.minicart.cart.on('checkout', function (evt) {\r\n");
      out.write("\t\t\tvar items = this.items(),\r\n");
      out.write("\t\t\t\tlen = items.length,\r\n");
      out.write("\t\t\t\ttotal = 0,\r\n");
      out.write("\t\t\t\ti;\r\n");
      out.write("\r\n");
      out.write("\t\t\t// Count the number of each item in the cart\r\n");
      out.write("\t\t\tfor (i = 0; i < len; i++) {\r\n");
      out.write("\t\t\t\ttotal += items[i].get('quantity');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (total < 3) {\r\n");
      out.write("\t\t\t\talert('The minimum order quantity is 3. Please add more to your shopping cart before checking out');\r\n");
      out.write("\t\t\t\tevt.preventDefault();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
