/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-29 21:49:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class search_002dintegrate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("author: W3layouts\r\n");
      out.write("author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>소공 5조-강산,치종,정훈</title>\r\n");
      out.write("<!-- for-mobile-apps -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Grocery Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,\r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("\t\tfunction hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\"  href=\"/images/sg.ico\"/>\r\n");
      out.write("<!-- //for-mobile-apps -->\r\n");
      out.write("<link href=\"css/bootstrap.css?ver=3\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/style.css?ver=3\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- //font-awesome icons -->\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<!-- //js -->\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event){\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("</head>\r\n");

Class.forName("com.mysql.jdbc.Driver");
String searchKey = "testing";
Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/shoppingmall", "root", "ks01");
Statement stmt = conn.createStatement();
String search = "select * from food where Genre ='"+searchKey+"';";
ResultSet rs = stmt.executeQuery(search);
//<li><a href="services.jsp">마트</a></li>
String testingst = "<li><a href=" + '"' + "services.jsp"+ '"' + ">Hi</a></li>";
String test = "<li style=" + '"' + "display: inline;" + '"' + ">Hello</li>";

      out.write("\r\n");
      out.write("\r\n");

if(rs.next())

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<div class=\"agileits_header\">\r\n");
      out.write("  <div class=\"w3l_offers\" style=\"margin-top: 8px;\">\r\n");
      out.write("    <a href=\"products.jsp\">5조 쇼핑몰</a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w3l_search\" style=\"margin-top: 10px;\">\r\n");
      out.write("    <form action=\"#\" method=\"post\">\r\n");
      out.write("      <input type=\"text\" name=\"Product\" value=\"물품 검색\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Search a product...';}\" required=\"\">\r\n");
      out.write("      <input type=\"submit\" value=\" \">\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"product_list_header\" style=\"padding: 6px, 2em, 6px 4px; margin-top: 10px;\">\r\n");
      out.write("    <form action=\"#\" method=\"post\" class=\"last\">\r\n");
      out.write("              <fieldset>\r\n");
      out.write("                  <input type=\"submit\" name=\"submit\" value=\"장바구니 보기\" class=\"button\" />\r\n");
      out.write("              </fieldset>\r\n");
      out.write("          </form>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!--  복붙할 구간 *************************************************************************************** -->\r\n");
      out.write("\r\n");
      out.write("  ");

    String sessionid = "";
    sessionid = (String)session.getAttribute("sessionid");
    if(sessionid == null || sessionid.equals("")){
      out.write("\r\n");
      out.write("    <div class=\"form\">\r\n");
      out.write("      <fieldset>\r\n");
      out.write("      <form action='#' method=\"post\">\r\n");
      out.write("      <div class =\"indexlogin\"><a href=\"login.jsp\">Login</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      </form>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("  </div>\r\n");
      out.write("  ");

  }else{
      out.write("\r\n");
      out.write("  <div></div>\r\n");
      out.write("  <form action = \"logout.jsp\" method = \"post\">\r\n");
      out.write("  <div style=\"padding-top: 20px;\">\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li style=\"display: inline-block; padding-right: 25px; padding-left: 25px;\">");
      out.print(sessionid );
      out.write("님 환영합니다.</li>\r\n");
      out.write("      <li style=\"display: inline-block; padding-right: 25px;\">\r\n");
      out.write("        <i class=\"fa fa-user\" aria-hidden=\"true\"> </i>\r\n");
      out.write("        <a href=\"#\">MyPage</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li style=\"display: inline-block; padding-right: 25px;\">\r\n");
      out.write("        <input type=\"submit\" value = \"로그아웃\">\r\n");
      out.write("      </li>\r\n");
      out.write("  </div>\r\n");
      out.write("  </form>\r\n");
}
      out.write("\r\n");
      out.write("  <!--  복붙할 구간 *************************************************************************************** -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"clearfix\"> </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- script-for sticky-nav -->\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("   var navoffeset=$(\".agileits_header\").offset().top;\r\n");
      out.write("   $(window).scroll(function(){\r\n");
      out.write("    var scrollpos=$(window).scrollTop();\r\n");
      out.write("    if(scrollpos >=navoffeset){\r\n");
      out.write("      $(\".agileits_header\").addClass(\"fixed\");\r\n");
      out.write("    }else{\r\n");
      out.write("      $(\".agileits_header\").removeClass(\"fixed\");\r\n");
      out.write("    }\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //script-for sticky-nav -->\r\n");
      out.write("<div class=\"logo_products\" style=\"padding-top: 80px;\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"w3ls_logo_products_left\">\r\n");
      out.write("      <h1><a href=\"index.jsp\"><span>Grocery</span> Store</a></h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3ls_logo_products_left1\">\r\n");
      out.write("      <ul class=\"special_items\">\r\n");
      out.write("        <li><a href=\"events.jsp\">모든 상품</a><i>/</i></li>\r\n");
      out.write("        <li><a href=\"about.jsp\">요리</a><i>/</i></li>\r\n");
      out.write("        <li><a href=\"products.jsp\">재료</a><i>/</i></li>\r\n");
      out.write("        <li><a href=\"services.jsp\">마트</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3ls_logo_products_left1\">\r\n");
      out.write("      <!-- 역 지오 코딩-->\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("      /*\r\n");
      out.write("        navigator.geolocation.getCurrentPosition(\r\n");
      out.write("        function initMap(position) {\r\n");
      out.write("            console.log('location load');\r\n");
      out.write("          var uluru = {lat: position.coords.latitude, lng:position.coords.longitude};\r\n");
      out.write("          var geocoder = new google.maps.Geocoder;\r\n");
      out.write("          geocodeLatLng(geocoder,uluru);\r\n");
      out.write("        });\r\n");
      out.write("        */\r\n");
      out.write("        function initMap() {\r\n");
      out.write("      }\r\n");
      out.write("        function getLocation() {\r\n");
      out.write("          if (navigator.geolocation) {\r\n");
      out.write("            navigator.geolocation.getCurrentPosition(onSuccess, onError);\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("        function onError(error) {\r\n");
      out.write("          alert('code: '    + error.code    + '\\n' +\r\n");
      out.write("          'message: ' + error.message + '\\n');\r\n");
      out.write("      }\r\n");
      out.write("        function onSuccess(position) {\r\n");
      out.write("          var uluru = {lat: position.coords.latitude, lng:position.coords.longitude};\r\n");
      out.write("          var geocoder = new google.maps.Geocoder;\r\n");
      out.write("         geocodeLatLng(geocoder,uluru);\r\n");
      out.write("      }\r\n");
      out.write("        function geocodeLatLng(geocoder,uluru) {\r\n");
      out.write("          var latlng = uluru;\r\n");
      out.write("          geocoder.geocode({'location': latlng}, function(results, status) {\r\n");
      out.write("            if (status === 'OK') {\r\n");
      out.write("              if (results[1]) {\r\n");
      out.write("                document.getElementById(\"now_location\").innerHTML =\" \"+ results[1].formatted_address;\r\n");
      out.write("              } else {\r\n");
      out.write("                document.getElementById(\"now_location\").innerHTML = \"위치를 찾을수 없습니다.\";\r\n");
      out.write("              }\r\n");
      out.write("            } else {\r\n");
      out.write("              document.getElementById(\"now_location\").innerHTML =\"위치확인이 불가합니다.\";\r\n");
      out.write("            }\r\n");
      out.write("          });\r\n");
      out.write("        }\r\n");
      out.write("      </script>\r\n");
      out.write("      <script async defer\r\n");
      out.write("      src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyAoJWfF7bE_v8AWgcksE52yTbQFoJ6jBPI&callback=initMap\">\r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("      <!-- -->\r\n");
      out.write("      <ul class=\"phone_email\">\r\n");
      out.write("        <a class=\"btn\" href=\"#\">\r\n");
      out.write("        <li><i class=\"fa fa-map-marker\" aria-hidden=\"true\" id=\"now_location\" onclick=\"getLocation()\">&nbsp;&nbsp;&nbsp;현재위치 확인</i></li></a>\r\n");
      out.write("        <li><i class=\"fa fa-envelope-o\" aria-hidden=\"true\"></i><a href=\"mailto:store@grocery.com\">store@grocery.com</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"clearfix\"> </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //header -->\r\n");
      out.write("<!-- banner -->\r\n");
      out.write("\t<div class=\"banner\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"w3l_banner_nav_center\">\r\n");
      out.write("\t\t\t<section class=\"slider\">\r\n");
      out.write("\t\t\t\t<div class=\"flexslider\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"slides\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3l_banner_nav_right_banner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Make your <span>food</span> with Spicy.</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"more\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"products.jsp\" class=\"button--saqui button--round-l button--text-thick\" data-text=\"Shop now\">Shop now</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3l_banner_nav_right_banner1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Make your <span>food</span> with Spicy.</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"more\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"products.jsp\" class=\"button--saqui button--round-l button--text-thick\" data-text=\"Shop now\">Shop now</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3l_banner_nav_right_banner2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>upto <i>50%</i> off.</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"more\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"products.jsp\" class=\"button--saqui button--round-l button--text-thick\" data-text=\"Shop now\">Shop now</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<!-- flexSlider -->\r\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" href=\"css/flexslider.css\" type=\"text/css\" media=\"screen\" property=\"\" />\r\n");
      out.write("\t\t\t\t<script defer src=\"js/jquery.flexslider.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t$(window).load(function(){\r\n");
      out.write("\t\t\t\t  $('.flexslider').flexslider({\r\n");
      out.write("\t\t\t\t\tanimation: \"slide\",\r\n");
      out.write("\t\t\t\t\tstart: function(slider){\r\n");
      out.write("\t\t\t\t\t  $('body').removeClass('loading');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t  });\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t  </script>\r\n");
      out.write("\t\t\t<!-- //flexSlider -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- banner -->\r\n");
      out.write("<div class=\"search\">\r\n");
      out.write("  <div class=\"panel-group w3l_panel_group_faq\" id=\"accordion\" aria-multiselectable=\"true\">\r\n");
      out.write("\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t  <div class=\"panel-heading\" role=\"tab\" id=\"headingFour\">\r\n");
      out.write("\t\t\t  <h4 class=\"panel-title asd\">통합검색 결과</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("  \t\t  <div class=\"panel-body panel_text\">\r\n");
      out.write("          <h3 style=\"text-align: left;\"> 혹시 이것을 찾으시나요? </h3>\r\n");
      out.write("          <div class=\"col-md-3 w3ls_w3l_banner_left w3ls_w3l_banner_left\" style=\"padding-left: 0px; padding-right: 0px;\">\r\n");
      out.write("  \t\t\t\t\t<div class=\"hover14 column\"></div>\r\n");
      out.write("  \t\t\t\t\t\t<div class=\"agile_top_brand_left_grid w3l_agile_top_brand_left_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"agile_top_brand_left_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"snipcart-item block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"snipcart-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"single.jsp\"><img src=\"images/64.png\" alt=\" \" class=\"img-responsive\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p> ");
      out.print(rs.getString(1));
      out.write(" </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>$10.0</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"snipcart-details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cmd\" value=\"_cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"add\" value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"business\" value=\" \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item_name\" value=\"pepper salami\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"amount\" value=\"10.00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"discount_amount\" value=\"1.00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"currency_code\" value=\"USD\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"return\" value=\" \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cancel_return\" value=\" \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Add to cart\" class=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("          <div class=\"col-md-3 w3ls_w3l_banner_left\" style=\"padding-left: 0px;\">\r\n");
      out.write("            <div class=\"agile_top_brand_left_grid1\" style=\"backgroud: white;\">\r\n");
      out.write("          \t   <h3 class=title style=\"font-size: small;\"> 요리설명 </h3>\r\n");
      out.write("               <p style=\"width: -webkit-fill-available; height: 170px; overflow: scroll;\">\r\n");
      out.write("                 ");
      out.print(rs.getString(3));
      out.write("\r\n");
      out.write("               </p>\r\n");
      out.write("               <h3 class=title style=\"font-size: small;\"> 필요재료 </h3>\r\n");
      out.write("\r\n");
      out.write("               ");

                     String[] sArray1 = rs.getString(3).split(",");
                     for (int i = 0; i < 5; i++){
                      // String plzs1 = "<li>" + sArray1[i] + "</li>";
                       String plz = "<li style=" + '"' + "display: inline;" + '"' + ">" + sArray1[i] + "</li>";
                       //String plzs = "<li>" + sArray1[i] + "</li>";
                       out.println(plz);
                     }
               
      out.write("\r\n");
      out.write("          \t</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 w3ls_w31_banner_left_reviews\" style=\"width: 20%\">\r\n");
      out.write("            <div class=\"agile_top_brand_left_grid1\" style=\"background: white;\">\r\n");
      out.write("              <h3 class=title style=\"font-size: small;\"> 네티즌 후기 </h3>\r\n");
      out.write("              <div class=\"list-group list-group-alternate\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("               ");

                  String[] sArray2 = rs.getString(3).split(",");
                  for (int i = 0; i < 5; i++){
                    String plz = "<a href=" + '"' + '#' + '"' + "class=" + '"' + "list-group-item" + '"' + ">" + sArray2[i] + "</a>";
                    out.println(plz);
                  }
               
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-3 w3ls_w3l_banner_left\" style=\"padding-left: 0px;\">\r\n");
      out.write("            <h3 class=title style=\"font-size: small;\"> 인근마트 </h3>\r\n");
      out.write("            <a class=\"btn\" href=\"#\">\r\n");
      out.write("              <i class=\"fa fa-map-marker\" aria-hidden=\"true\"\r\n");
      out.write("                id=\"now_location\" onclick=\"getLocation()\">&nbsp;&nbsp;&nbsp;현재위치로 검색하기!</i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <div id=\"map\" style=\"width: 120%; height:350px; background-color: grey;\"> </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- address에 검색값 input !!!!-->\r\n");
      out.write("            <script>\r\n");
      out.write("\r\n");
      out.write("            function initMap() {\r\n");
      out.write("             var map = new google.maps.Map(document.getElementById('map'), {\r\n");
      out.write("               zoom: 15,\r\n");
      out.write("               center: {lat:37.5575367,lng:127.0007751}\r\n");
      out.write("             });\r\n");
      out.write("             var geocoder = new google.maps.Geocoder();\r\n");
      out.write("            ////////////address에 검색값 input!!!!\r\n");
      out.write("             var address =\"명동\";\r\n");
      out.write("             geocodeAddress(address,geocoder, map);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("             function geocodeAddress(address,geocoder, resultsMap) {\r\n");
      out.write("             geocoder.geocode({'address': address}, function(results, status) {\r\n");
      out.write("                 if (status === 'OK') {\r\n");
      out.write("                   resultsMap.setCenter(results[0].geometry.location);\r\n");
      out.write("                 var input_content = '<p>'+results[0].formatted_address+'</p>';\r\n");
      out.write("                 makemarker(\"검색위치\",\"./images/cheering_minions.gif\",input_content,resultsMap,\r\n");
      out.write("                  results[0].geometry.location.lat(), results[0].geometry.location.lng())\r\n");
      out.write("\r\n");
      out.write("                   //  qurry( resultsMap,lat(),lng()) -> makemarker\r\n");
      out.write("\r\n");
      out.write("                 } else {\r\n");
      out.write("                 //  alert('위치검색이 안되서 \"동국대\"로 보여드릴게요!');\r\n");
      out.write("                   resultsMap.setCenter({lat:37.5575367,lng:127.0007751});\r\n");
      out.write("                   input_content =  '<p>학생들의 건강을 고려해 언덕에 지어졌죠.<br>'+\r\n");
      out.write("                                   '컴공과 학생들이 가끔 아픈건 안 비밀</p>'+\r\n");
      out.write("                                   'ps.아..컴공과는 엘레베이터타고 다니죠..';\r\n");
      out.write("                   makemarker(\"동국대학교\",\"./images/dongguk.jpg\",input_content,resultsMap,\r\n");
      out.write("                    37.5575367,127.0007751)\r\n");
      out.write("                 }\r\n");
      out.write("               });\r\n");
      out.write("             }\r\n");
      out.write("\r\n");
      out.write("             function makemarker(head_D,img_D,content_D,resultsMap,lat_D,lng_D){\r\n");
      out.write("                 //resultsMap.setCenter({lat:37.5575367,lng:127.0007751});\r\n");
      out.write("                 var infowindow = new google.maps.InfoWindow({\r\n");
      out.write("                   content: '<h1><b>'+ head_D +'</b></h1>'+\r\n");
      out.write("                           '<img src=\"'+img_D+ '\"alt=\"ㅠㅠ사진불러오기실패\" height=\"130\" width=\"170\"><br>'+\r\n");
      out.write("                            \"'\"+content_D+\"'\"\r\n");
      out.write("                 })\r\n");
      out.write("               var marker = new google.maps.Marker({\r\n");
      out.write("                 map: resultsMap,\r\n");
      out.write("                 position: {lat: lat_D,lng:lng_D},\r\n");
      out.write("                 title : '클릭하면 더 자세한 정보를 보여드려요!'\r\n");
      out.write("               });\r\n");
      out.write("               marker.addListener('click', function() {\r\n");
      out.write("                 infowindow.open(map, marker);\r\n");
      out.write("               });\r\n");
      out.write("             }\r\n");
      out.write("\r\n");
      out.write("             function getLocation() {\r\n");
      out.write("               navigator.geolocation.getCurrentPosition(\r\n");
      out.write("                 function initMap(position) {\r\n");
      out.write("                   var lat = position.coords.latitude + \",\"+position.coords.longitude;\r\n");
      out.write("                   var address2 = lat;\r\n");
      out.write("                //   var geocoder = new google.maps.Geocoder();\r\n");
      out.write("                   var map2 = new google.maps.Map(document.getElementById('map'), {\r\n");
      out.write("                     zoom:15,\r\n");
      out.write("                     center: {lat:37.5575367,lng:127.0007751}\r\n");
      out.write("                   });\r\n");
      out.write("                    var geocoder2 = new google.maps.Geocoder();\r\n");
      out.write("                   geocodeAddress(address2,geocoder2, map2);\r\n");
      out.write("                 }\r\n");
      out.write("               );\r\n");
      out.write("             }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </script>\r\n");
      out.write("\r\n");
      out.write("            <script async defer\r\n");
      out.write("            src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyAoJWfF7bE_v8AWgcksE52yTbQFoJ6jBPI&callback=initMap\">\r\n");
      out.write("            </script>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("           </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t <div class=\"panel-heading\" role=\"tab\" id=\"headingFive\">\r\n");
      out.write("\t\t\t\t  <h4 class=\"panel-title asd\">\r\n");
      out.write("\t\t\t\t\t<a class=\"pa_italic collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseFive\" aria-expanded=\"false\" aria-controls=\"collapseFive\">\r\n");
      out.write("\t\t\t\t\t  <span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span><i class=\"glyphicon glyphicon-minus\" aria-hidden=\"true\"></i>요리검색 결과\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t  </h4>\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t <div id=\"collapseFive\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingFive\" aria-expanded=\"false\" style=\"height: 0px;\">\r\n");
      out.write("\t\t\t\t   <div class=\"panel-body panel_text\">\r\n");
      out.write("             <h3 style=\"text-align: left;\"> 요리이름 </h3>\r\n");
      out.write("             <div class=\"col-md-3 w3ls_w3l_banner_left w3ls_w3l_banner_left\" style=\"padding-left: 0px; padding-right: 0px;\">\r\n");
      out.write("     \t\t\t\t\t<div class=\"hover14 column\"></div>\r\n");
      out.write("     \t\t\t\t\t\t<div class=\"agile_top_brand_left_grid w3l_agile_top_brand_left_grid\">\r\n");
      out.write("   \t\t\t\t\t\t\t<div class=\"agile_top_brand_left_grid1\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t<div class=\"snipcart-item block\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t<div class=\"snipcart-thumb\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t<a href=\"single.jsp\"><img src=\"images/64.png\" alt=\" \" class=\"img-responsive\"></a>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t<p>pepper salami (250 gm)</p>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t<h4>$10.0</h4>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t<div class=\"snipcart-details\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cmd\" value=\"_cart\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"add\" value=\"1\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"business\" value=\" \">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item_name\" value=\"pepper salami\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"amount\" value=\"10.00\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"discount_amount\" value=\"1.00\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"currency_code\" value=\"USD\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"return\" value=\" \">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cancel_return\" value=\" \">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Add to cart\" class=\"button\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("   \t\t\t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\t</div>\r\n");
      out.write("            <div class=\"col-md-3 w3ls_w3l_banner_left\" style=\"padding-left: 0px;\">\r\n");
      out.write("              <div class=\"agile_top_brand_left_grid1\" style=\"backgroud: white;\">\r\n");
      out.write("            \t   <h3 class=title style=\"font-size: small;\"> 요리설명 </h3>\r\n");
      out.write("                 <p style=\"width: -webkit-fill-available; height: 170px; overflow: scroll;\">\r\n");
      out.write("                   \"한국 요리(韓國料理, 문화어: 조선 료리)는 한국의 음식을 뜻한다. 복잡한 궁중 요리에서부터 지방의 특색 요리와 현대의 퓨전 요리에 이르기까지 재료와 조리법이 매우 다양하다. 전통적인 한국 정식은 밥, 국, 김치와 함께 나오는 많은 반찬들로 이루어진다. 한국 요리는 주로 쌀을 기반으로. 일반적으로 사용되는 성분 포함 참기름, 된장, 간장, 소금, 마늘, 생강, 다시마국물그리고 고추장 등으로 맛을 낸다. 김치는 거의 항상 모든 음식에서 제공된다. 식단은 계절별로 다양한데, 전통적으로 겨울 동안에는 마당에 구멍을 파고 땅 속에 묻어 놓은 장독에 저장된 김치와 그 밖에 절인 채소들에 많이 의존했다. 그러나 현재는 계절에 상관없이 대부분의 식단을 맛볼 수 있다.\"\r\n");
      out.write("                 </p>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 w3ls_w3l_banner_left\">\r\n");
      out.write("              <div class=\"hover14 column\"></div>\r\n");
      out.write("              <div class=\"agile_top_brand_left_grid1\" style=\"background: white;\">\r\n");
      out.write("                <h3 class=title style=\"font-size: small;\"> 필요재료 </h3>\r\n");
      out.write("                <li> 재료1 </li>\r\n");
      out.write("                <li> 재료2 </li>\r\n");
      out.write("                <li> 재료3 </li>\r\n");
      out.write("                <li> 아주긴재료이름름름4 </li>\r\n");
      out.write("                <div class=\"snipcart-details\">\r\n");
      out.write("                  <form action=\"#\" method=\"post\">\r\n");
      out.write("                    <fieldset>\r\n");
      out.write("                      <input type=\"hidden\" name=\"cmd\" value=\"_cart\">\r\n");
      out.write("                      <input type=\"hidden\" name=\"add\" value=\"1\">\r\n");
      out.write("                      <input type=\"hidden\" name=\"business\" value=\" \">\r\n");
      out.write("                      <input type=\"hidden\" name=\"item_name\" value=\"pepper salami\">\r\n");
      out.write("                      <input type=\"hidden\" name=\"amount\" value=\"10.00\">\r\n");
      out.write("                      <input type=\"hidden\" name=\"discount_amount\" value=\"1.00\">\r\n");
      out.write("                      <input type=\"hidden\" name=\"currency_code\" value=\"USD\">\r\n");
      out.write("                      <input type=\"hidden\" name=\"return\" value=\" \">\r\n");
      out.write("                      <input type=\"hidden\" name=\"cancel_return\" value=\" \">\r\n");
      out.write("                      <input type=\"submit\" name=\"submit\" value=\"장바구니 일괄담기\" class=\"button\">\r\n");
      out.write("                    </fieldset>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 w3ls_w3l_banner_left\" style=\"width: 25%;\">\r\n");
      out.write("              <div class=\"hover14 column\"></div>\r\n");
      out.write("              <div class=\"agile_top_brand_left_grid1\" style=\"background: white;\">\r\n");
      out.write("              <h3 class=\"title\" style=\"font-size: small;\"> '요리이름'과 비슷한 요리 </h3>\r\n");
      out.write("              <div class=\"list-group list-group-alternate\" style=\"margin-bottom: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t   <a href=\"#\" class=\"list-group-item\"> '요리1이름' 간단한 설명~~ </a>\r\n");
      out.write("\t\t\t\t\t\t   <a href=\"#\" class=\"list-group-item\"> 요리2 </a>\r\n");
      out.write("\t\t\t\t\t\t   <a href=\"#\" class=\"list-group-item\"> 요리3 </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <h3 class=\"title\" style=\"font-size: small;\"> '요리이름'와 잘 어울려요~! </h3>\r\n");
      out.write("              <div class=\"list-group list-group-alternate\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("               <a href=\"#\" class=\"list-group-item\"> 요리1 </a>\r\n");
      out.write(" \t\t\t\t\t\t   <a href=\"#\" class=\"list-group-item\"> 요리2 </a>\r\n");
      out.write(" \t\t\t\t\t\t   <a href=\"#\" class=\"list-group-item\"> 요리3 </a>\r\n");
      out.write("              </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t   </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t   <div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\" role=\"tab\" id=\"headingSix\">\r\n");
      out.write("\t\t\t\t  <h4 class=\"panel-title asd\">\r\n");
      out.write("\t\t\t\t\t<a class=\"pa_italic collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseSix\" aria-expanded=\"false\" aria-controls=\"collapseSix\">\r\n");
      out.write("\t\t\t\t\t  <span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span><i class=\"glyphicon glyphicon-minus\" aria-hidden=\"true\"></i>재료검색 결과\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t  </h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"collapseSix\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingSix\" aria-expanded=\"false\" style=\"height: 0px;\">\r\n");
      out.write("\t\t\t\t   <div class=\"panel-body panel_text\">\r\n");
      out.write("\t\t\t\t\tNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t   <div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\" role=\"tab\" id=\"headingSeven\">\r\n");
      out.write("\t\t\t\t  <h4 class=\"panel-title asd\">\r\n");
      out.write("\t\t\t\t\t<a class=\"pa_italic collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseSeven\" aria-expanded=\"false\" aria-controls=\"collapseSeven\">\r\n");
      out.write("\t\t\t\t\t  <span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span><i class=\"glyphicon glyphicon-minus\" aria-hidden=\"true\"></i>마트검색 결과\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t  </h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"collapseSeven\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingSeven\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t   <div class=\"panel-body panel_text\">\r\n");
      out.write("\t\t\t\t\tNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- top-brands -->\r\n");
      out.write("<!-- //top-brands -->\r\n");
      out.write("<!-- fresh-vegetables -->\r\n");
      out.write("<!-- //fresh-vegetables -->\r\n");
      out.write("<!-- newsletter -->\r\n");
      out.write("\t<div class=\"newsletter\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"w3agile_newsletter_left\">\r\n");
      out.write("\t\t\t\t<h3>sign up for our newsletter</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3agile_newsletter_right\">\r\n");
      out.write("\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"email\" name=\"Email\" value=\"Email\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Email';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"subscribe now\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //newsletter -->\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>information</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"events.jsp\">Events</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"about.jsp\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"products.jsp\">Best Deals</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"services.jsp\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"short-codes.jsp\">Short Codes</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>policy info</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"faqs.jsp\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"privacy.jsp\">privacy policy</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"privacy.jsp\">terms of use</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>what in stores</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"pet.jsp\">Pet Food</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"frozen.jsp\">Frozen Snacks</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"kitchen.jsp\">Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"products.jsp\">Branded Foods</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"household.jsp\">Households</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>twitter posts</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list1\">\r\n");
      out.write("\t\t\t\t\t<li><label class=\"fa fa-twitter\" aria-hidden=\"true\"></label><i>01 day ago</i><span>Non numquam <a href=\"#\">http://sd.ds/13jklf#</a>\r\n");
      out.write("\t\t\t\t\t\teius modi tempora incidunt ut labore et\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">http://sd.ds/1389kjklf#</a>quo nulla.</span></li>\r\n");
      out.write("\t\t\t\t\t<li><label class=\"fa fa-twitter\" aria-hidden=\"true\"></label><i>02 day ago</i><span>Con numquam <a href=\"#\">http://fd.uf/56hfg#</a>\r\n");
      out.write("\t\t\t\t\t\teius modi tempora incidunt ut labore et\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">http://fd.uf/56hfg#</a>quo nulla.</span></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t<div class=\"agile_footer_grids\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 w3_footer_grid agile_footer_grids_w3_footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3_footer_grid_bottom\">\r\n");
      out.write("\t\t\t\t\t\t<h4>100% secure payments</h4>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/card.png\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 w3_footer_grid agile_footer_grids_w3_footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3_footer_grid_bottom\">\r\n");
      out.write("\t\t\t\t\t\t<h5>connect with us</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"agileits_social_icons\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"google\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"instagram\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"dribbble\"><i class=\"fa fa-dribbble\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"wthree_footer_copy\">\r\n");
      out.write("\t\t\t\t<p>�� 2016 Grocery Store. All rights reserved | Design by <a href=\"http://w3layouts.com/\">W3layouts</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //footer -->\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\".dropdown\").hover(\r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideDown(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');\r\n");
      out.write("        },\r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideUp(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');\r\n");
      out.write("        }\r\n");
      out.write("    );\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- here stars scrolling icon -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\teasingType: 'linear'\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\t$().UItoTop({ easingType: 'easeOutQuart' });\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //here ends scrolling icon -->\r\n");
      out.write("<script src=\"js/minicart.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\tpaypal.minicart.render();\r\n");
      out.write("\t\tpaypal.minicart.cart.on('checkout', function (evt) {\r\n");
      out.write("\t\t\tvar items = this.items(),\r\n");
      out.write("\t\t\t\tlen = items.length,\r\n");
      out.write("\t\t\t\ttotal = 0,\r\n");
      out.write("\t\t\t\ti;\r\n");
      out.write("\t\t\t// Count the number of each item in the cart\r\n");
      out.write("\t\t\tfor (i = 0; i < len; i++) {\r\n");
      out.write("\t\t\t\ttotal += items[i].get('quantity');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (total < 3) {\r\n");
      out.write("\t\t\t\talert('The minimum order quantity is 3. Please add more to your shopping cart before checking out');\r\n");
      out.write("\t\t\t\tevt.preventDefault();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("  <script type=\"txt/javascript\">\r\n");
      out.write("    document.write(\"<p>This is 'MsgWindow'. I am 200px wide and 100px tall!</p>\");\r\n");
      out.write("    var jbString = rs.getString(3);\r\n");
      out.write("    var jbSplit = jbString.split(',');\r\n");
      out.write("    for ( var i in jbSplit) {\r\n");
      out.write("      document.write( '<h3>' + jbSplit[i] + '</h3>');\r\n");
      out.write("      <h3> jbSplit[i] </h3>\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
